//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Game.Hotfix.Cfg
{

public sealed partial class TbTest
{
    private readonly Dictionary<int, Item.Test> _dataMap;
    private readonly List<Item.Test> _dataList;
    
    public TbTest(JSONNode _json)
    {
        _dataMap = new Dictionary<int, Item.Test>();
        _dataList = new List<Item.Test>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Item.Test.DeserializeTest(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Item.Test> DataMap => _dataMap;
    public List<Item.Test> DataList => _dataList;

    public Item.Test GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Item.Test Get(int key) => _dataMap[key];
    public Item.Test this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}